changelog:
  exclude:
    labels:
      - 'Release'

  categories:
    - title: Breaking Changes
      labels: ['Breaking Change']
    - title: Features
      labels: ['Feature']
    - title: Bug Fixes
      labels: ['Bug']
    - title: Documentation
      labels: ['Documentation']
    - title: Refactoring
      labels: ['Refactoring']
    - title: Testing
      labels: ['Testing']
    - title: Maintenance
      labels: ['Maintenance']
    - title: CI
      labels: ['CI']
    - title: Dependency Updates
      labels: ['Dependencies', "dependencies"]
    - title: Other Changes
      labels: ['*']