# シナリオ固有設定ファイル
# 共通設定は config/common-database-config.yaml で定義
# ここではシナリオ固有の情報のみを記述

name: example-01-basic-setup
description: 基本セットアップのサンプル
version: "1.0"

# シナリオ固有のファイルパス設定
scenario_files:
  primary-db:
    seed: seed-data/primary-seed.json
    expected: expected-primary.yaml
  
  secondary-db:
    seed: seed-data/secondary-seed.json
    expected: expected-secondary.yaml