# Scenario-specific configuration file
# Common settings are defined in config/common-database-config.yaml
# Only scenario-specific information is described here

name: scenario-01-basic-setup
description: Basic setup sample for single database
version: "1.0"

# Scenario-specific file path settings
scenario_files:
  fixtures: fixtures/
  expected-primary: expected-primary.yaml