# Common database configuration file
# Define common DB settings, schema paths, and default values for all scenarios

databases:
  primary-db:
    name: Primary Database
    schema: <YOUR_PRIMARY_SCHEMA_PATH>
  
  secondary-db:
    name: Secondary Database
    schema: <YOUR_SECONDARY_SCHEMA_PATH>

# Default execution steps
default_steps:
  - start_emulator
  - setup_databases: [primary-db, secondary-db]
  - validate_databases: [primary-db, secondary-db]

# Default configuration values
defaults:
  timeout: 300
  retry_count: 1
  cleanup:
    temp_files: true
    stop_emulator: false

# Common success criteria template
success_criteria_template:
  - "Expected data exists in all tables of Primary DB"
  - "Expected data exists in all tables of Secondary DB"
  - "All expected values match"