name: Auto Label PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto label PR based on title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          echo "Analyzing PR title: $PR_TITLE"
          
          # Function to add label
          add_label() {
            local label="$1"
            echo "Adding label: $label"
            gh pr edit $PR_NUMBER --add-label "$label" --repo ${{ github.repository }}
          }
          
          # Remove existing auto-labels first (optional cleanup)
          # gh pr edit $PR_NUMBER --remove-label "Feature,Bug,Documentation,Refactoring,Testing,Maintenance,CI" --repo ${{ github.repository }} 2>/dev/null || true
          
          # Analyze title and add appropriate labels
          case "$PR_TITLE" in
            feat:*|feat\(*|"feat "*|"feature:"*|"Feature:"*)
              add_label "Feature"
              ;;
            fix:*|fix\(*|"fix "*|"bugfix:"*|"Fix:"*)
              add_label "Bug"
              ;;
            docs:*|docs\(*|"docs "*|"doc:"*|"documentation:"*)
              add_label "Documentation"
              ;;
            refactor:*|refactor\(*|"refactor "*|"Refactor:"*)
              add_label "Refactoring"
              ;;
            test:*|test\(*|"test "*|"tests:"*)
              add_label "Testing"
              ;;
            chore:*|chore\(*|"chore "*|"maintenance:"*)
              add_label "Maintenance"
              ;;
            ci:*|ci\(*|"ci "*|"CI:"*|"workflow:"*)
              add_label "CI"
              ;;
            perf:*|perf\(*|"perf "*|"performance:"*)
              add_label "Feature"  # Performance improvements are often features
              ;;
            style:*|style\(*|"style "*)
              add_label "Maintenance"  # Style changes are maintenance
              ;;
            build:*|build\(*|"build "*)
              add_label "CI"  # Build changes are CI-related
              ;;
            revert:*|revert\(*|"revert "*|"Revert "*)
              add_label "Maintenance"  # Reverts are maintenance
              ;;
            *)
              echo "No conventional commit pattern found in title. Skipping auto-labeling."
              ;;
          esac
        env:
          GH_TOKEN: ${{ github.token }}