name: Check PR title prefix

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          echo "PR title: '${{ github.event.pull_request.title }}'"
          TITLE="${{ github.event.pull_request.title }}"
          if ! echo "$TITLE" | grep -Eq '^(Revert|feat|fix|docs|chore|refactor|test|perf)(\(.+\))?: '; then
            echo "❌ PR title must start with a Conventional Commit prefix like 'feat:', 'fix:', etc."
            exit 1
          fi
